apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: false
  - name: Loki
    uid: loki-ds
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo-ds
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
  - name: Tempo
    uid: tempo-ds
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus-ds'
  - name: Pyroscope
    uid: pyroscope-ds
    type: grafana-pyroscope-datasource
    access: proxy
    orgId: 1
    url: http://pyroscope:4040
    isDefault: false
    jsonData:
      keepCookies: [pyroscope_git_session]
