auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

  otlp_config:
    resource_attributes:
      ignore_defaults: true
      attributes_config:
        - action: index_label
          attributes:
            - service.name
            - service.version
            - deployment.environment
    log_attributes:
      - action: index_label
        attributes:
          - scope_name
          - level

ruler:
  storage:
    type: local
    local:
      directory: /var/loki/rules
  # alertmanager_url: http://alertmanager:9093
