// Code generated by "stringer -type CircuitState -trimprefix CircuitState"; DO NOT EDIT.

package httpclient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateClosed-0]
	_ = x[StateHalfOpen-1]
	_ = x[StateOpen-2]
}

const _CircuitState_name = "StateClosedStateHalfOpenStateOpen"

var _CircuitState_index = [...]uint8{0, 11, 24, 33}

func (i CircuitState) String() string {
	if i < 0 || i >= CircuitState(len(_CircuitState_index)-1) {
		return "CircuitState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CircuitState_name[_CircuitState_index[i]:_CircuitState_index[i+1]]
}
