// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package profiles

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Event struct {
	Id              string         `json:"id"`
	Slug            string         `json:"slug"`
	Kind            string         `json:"kind"`
	EventPictureUri sql.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	TimeStart       time.Time      `json:"timeStart"`
	TimeEnd         time.Time      `json:"timeEnd"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
	SeriesId        sql.NullString `json:"seriesId"`
	Status          string         `json:"status"`
	AttendanceUri   sql.NullString `json:"attendanceUri"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
}

type EventAttendance struct {
	Id        string       `json:"id"`
	EventId   string       `json:"eventId"`
	ProfileId string       `json:"profileId"`
	Kind      string       `json:"kind"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type EventSeries struct {
	Id              string         `json:"id"`
	Slug            string         `json:"slug"`
	EventPictureUri sql.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type Profile struct {
	Id                string                `json:"id"`
	Slug              string                `json:"slug"`
	Kind              string                `json:"kind"`
	CustomDomain      sql.NullString        `json:"customDomain"`
	ProfilePictureUri sql.NullString        `json:"profilePictureUri"`
	Pronouns          sql.NullString        `json:"pronouns"`
	Title             string                `json:"title"`
	Description       string                `json:"description"`
	Properties        pqtype.NullRawMessage `json:"properties"`
	CreatedAt         time.Time             `json:"createdAt"`
	UpdatedAt         sql.NullTime          `json:"updatedAt"`
	DeletedAt         sql.NullTime          `json:"deletedAt"`
}

type ProfileLink struct {
	Id                        string                `json:"id"`
	ProfileId                 string                `json:"profileId"`
	Kind                      string                `json:"kind"`
	Order                     int32                 `json:"order"`
	IsManaged                 bool                  `json:"isManaged"`
	IsVerified                bool                  `json:"isVerified"`
	RemoteId                  sql.NullString        `json:"remoteId"`
	PublicId                  sql.NullString        `json:"publicId"`
	Uri                       sql.NullString        `json:"uri"`
	Title                     string                `json:"title"`
	AuthProvider              string                `json:"authProvider"`
	AuthAccessTokenScope      string                `json:"authAccessTokenScope"`
	AuthAccessToken           string                `json:"authAccessToken"`
	AuthAccessTokenExpiresAt  sql.NullTime          `json:"authAccessTokenExpiresAt"`
	AuthRefreshToken          sql.NullString        `json:"authRefreshToken"`
	AuthRefreshTokenExpiresAt sql.NullTime          `json:"authRefreshTokenExpiresAt"`
	Properties                pqtype.NullRawMessage `json:"properties"`
	CreatedAt                 time.Time             `json:"createdAt"`
	UpdatedAt                 sql.NullTime          `json:"updatedAt"`
	DeletedAt                 sql.NullTime          `json:"deletedAt"`
}

type ProfileLinkImport struct {
	Id            string                `json:"id"`
	ProfileLinkId string                `json:"profileLinkId"`
	RemoteId      sql.NullString        `json:"remoteId"`
	Properties    pqtype.NullRawMessage `json:"properties"`
	CreatedAt     time.Time             `json:"createdAt"`
	UpdatedAt     sql.NullTime          `json:"updatedAt"`
	DeletedAt     sql.NullTime          `json:"deletedAt"`
}

type ProfileMembership struct {
	Id         string                `json:"id"`
	ProfileId  string                `json:"profileId"`
	UserId     string                `json:"userId"`
	Kind       string                `json:"kind"`
	Properties pqtype.NullRawMessage `json:"properties"`
	CreatedAt  time.Time             `json:"createdAt"`
	UpdatedAt  sql.NullTime          `json:"updatedAt"`
	DeletedAt  sql.NullTime          `json:"deletedAt"`
}

type ProfilePage struct {
	Id              string         `json:"id"`
	ProfileId       string         `json:"profileId"`
	Slug            string         `json:"slug"`
	Order           int32          `json:"order"`
	CoverPictureUri sql.NullString `json:"coverPictureUri"`
	Title           string         `json:"title"`
	Summary         string         `json:"summary"`
	Content         string         `json:"content"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type Question struct {
	Id            string         `json:"id"`
	UserId        string         `json:"userId"`
	ProfileId     sql.NullString `json:"profileId"`
	Content       string         `json:"content"`
	IsHidden      bool           `json:"isHidden"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     sql.NullTime   `json:"updatedAt"`
	DeletedAt     sql.NullTime   `json:"deletedAt"`
	AnsweredAt    sql.NullTime   `json:"answeredAt"`
	AnswerUri     sql.NullString `json:"answerUri"`
	IsAnonymous   bool           `json:"isAnonymous"`
	AnswerKind    sql.NullString `json:"answerKind"`
	AnswerContent sql.NullString `json:"answerContent"`
}

type QuestionVote struct {
	Id         string    `json:"id"`
	QuestionId string    `json:"questionId"`
	UserId     string    `json:"userId"`
	Score      int32     `json:"score"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	Id                       string         `json:"id"`
	Status                   string         `json:"status"`
	OauthRequestState        string         `json:"oauthRequestState"`
	OauthRequestCodeVerifier string         `json:"oauthRequestCodeVerifier"`
	OauthRedirectUri         sql.NullString `json:"oauthRedirectUri"`
	LoggedInUserId           sql.NullString `json:"loggedInUserId"`
	LoggedInAt               sql.NullTime   `json:"loggedInAt"`
	ExpiresAt                sql.NullTime   `json:"expiresAt"`
	CreatedAt                time.Time      `json:"createdAt"`
	UpdatedAt                sql.NullTime   `json:"updatedAt"`
}

type Story struct {
	Id              string                `json:"id"`
	AuthorProfileId sql.NullString        `json:"authorProfileId"`
	Slug            string                `json:"slug"`
	Kind            string                `json:"kind"`
	Status          string                `json:"status"`
	IsFeatured      sql.NullBool          `json:"isFeatured"`
	StoryPictureUri sql.NullString        `json:"storyPictureUri"`
	Title           string                `json:"title"`
	Summary         string                `json:"summary"`
	Content         string                `json:"content"`
	Properties      pqtype.NullRawMessage `json:"properties"`
	PublishedAt     sql.NullTime          `json:"publishedAt"`
	CreatedAt       time.Time             `json:"createdAt"`
	UpdatedAt       sql.NullTime          `json:"updatedAt"`
	DeletedAt       sql.NullTime          `json:"deletedAt"`
}

type User struct {
	Id                  string         `json:"id"`
	Kind                string         `json:"kind"`
	Name                string         `json:"name"`
	Email               sql.NullString `json:"email"`
	Phone               sql.NullString `json:"phone"`
	GithubHandle        sql.NullString `json:"githubHandle"`
	GithubRemoteId      sql.NullString `json:"githubRemoteId"`
	BskyHandle          sql.NullString `json:"bskyHandle"`
	BskyRemoteId        sql.NullString `json:"bskyRemoteId"`
	XHandle             sql.NullString `json:"xHandle"`
	XRemoteId           sql.NullString `json:"xRemoteId"`
	IndividualProfileId sql.NullString `json:"individualProfileId"`
	CreatedAt           time.Time      `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
	DeletedAt           sql.NullTime   `json:"deletedAt"`
}

type CreateProfileParams struct {
	Id   string `json:"id"`
	Slug string `json:"slug"`
}

type UpdateProfileParams struct {
	Slug string `json:"slug"`
	Id   string `json:"id"`
}
