// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Cache struct {
	Key       string                `db:"key" json:"key"`
	Value     pqtype.NullRawMessage `db:"value" json:"value"`
	UpdatedAt time.Time             `db:"updated_at" json:"updated_at"`
}

type Event struct {
	ID              string         `db:"id" json:"id"`
	Slug            string         `db:"slug" json:"slug"`
	Kind            string         `db:"kind" json:"kind"`
	EventPictureURI sql.NullString `db:"event_picture_uri" json:"event_picture_uri"`
	Title           string         `db:"title" json:"title"`
	Description     string         `db:"description" json:"description"`
	TimeStart       time.Time      `db:"time_start" json:"time_start"`
	TimeEnd         time.Time      `db:"time_end" json:"time_end"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	SeriesID        sql.NullString `db:"series_id" json:"series_id"`
	Status          string         `db:"status" json:"status"`
	AttendanceURI   sql.NullString `db:"attendance_uri" json:"attendance_uri"`
	PublishedAt     sql.NullTime   `db:"published_at" json:"published_at"`
}

type EventAttendance struct {
	ID        string       `db:"id" json:"id"`
	EventID   string       `db:"event_id" json:"event_id"`
	ProfileID string       `db:"profile_id" json:"profile_id"`
	Kind      string       `db:"kind" json:"kind"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type EventSeries struct {
	ID              string         `db:"id" json:"id"`
	Slug            string         `db:"slug" json:"slug"`
	EventPictureURI sql.NullString `db:"event_picture_uri" json:"event_picture_uri"`
	Title           string         `db:"title" json:"title"`
	Description     string         `db:"description" json:"description"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type Profile struct {
	ID                string                `db:"id" json:"id"`
	Slug              string                `db:"slug" json:"slug"`
	Kind              string                `db:"kind" json:"kind"`
	CustomDomain      sql.NullString        `db:"custom_domain" json:"custom_domain"`
	ProfilePictureURI sql.NullString        `db:"profile_picture_uri" json:"profile_picture_uri"`
	Pronouns          sql.NullString        `db:"pronouns" json:"pronouns"`
	Properties        pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt         time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt         sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt         sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfileLink struct {
	ID                        string                `db:"id" json:"id"`
	ProfileID                 string                `db:"profile_id" json:"profile_id"`
	Kind                      string                `db:"kind" json:"kind"`
	Order                     int32                 `db:"order" json:"order"`
	IsManaged                 bool                  `db:"is_managed" json:"is_managed"`
	IsVerified                bool                  `db:"is_verified" json:"is_verified"`
	IsHidden                  bool                  `db:"is_hidden" json:"is_hidden"`
	RemoteID                  sql.NullString        `db:"remote_id" json:"remote_id"`
	PublicID                  sql.NullString        `db:"public_id" json:"public_id"`
	URI                       sql.NullString        `db:"uri" json:"uri"`
	Title                     string                `db:"title" json:"title"`
	AuthProvider              sql.NullString        `db:"auth_provider" json:"auth_provider"`
	AuthAccessTokenScope      sql.NullString        `db:"auth_access_token_scope" json:"auth_access_token_scope"`
	AuthAccessToken           sql.NullString        `db:"auth_access_token" json:"auth_access_token"`
	AuthAccessTokenExpiresAt  sql.NullTime          `db:"auth_access_token_expires_at" json:"auth_access_token_expires_at"`
	AuthRefreshToken          sql.NullString        `db:"auth_refresh_token" json:"auth_refresh_token"`
	AuthRefreshTokenExpiresAt sql.NullTime          `db:"auth_refresh_token_expires_at" json:"auth_refresh_token_expires_at"`
	Properties                pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt                 time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt                 sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt                 sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfileLinkImport struct {
	ID            string                `db:"id" json:"id"`
	ProfileLinkID string                `db:"profile_link_id" json:"profile_link_id"`
	RemoteID      sql.NullString        `db:"remote_id" json:"remote_id"`
	Properties    pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt     time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfileMembership struct {
	ID              string                `db:"id" json:"id"`
	ProfileID       string                `db:"profile_id" json:"profile_id"`
	MemberProfileID string                `db:"member_profile_id" json:"member_profile_id"`
	Kind            string                `db:"kind" json:"kind"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	StartedAt       sql.NullTime          `db:"started_at" json:"started_at"`
	FinishedAt      sql.NullTime          `db:"finished_at" json:"finished_at"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfilePage struct {
	ID              string         `db:"id" json:"id"`
	ProfileID       string         `db:"profile_id" json:"profile_id"`
	Slug            string         `db:"slug" json:"slug"`
	Order           int32          `db:"order" json:"order"`
	CoverPictureURI sql.NullString `db:"cover_picture_uri" json:"cover_picture_uri"`
	PublishedAt     sql.NullTime   `db:"published_at" json:"published_at"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type ProfilePageTx struct {
	ProfilePageID string `db:"profile_page_id" json:"profile_page_id"`
	LocaleCode    string `db:"locale_code" json:"locale_code"`
	Title         string `db:"title" json:"title"`
	Summary       string `db:"summary" json:"summary"`
	Content       string `db:"content" json:"content"`
}

type ProfileTx struct {
	ProfileID   string                `db:"profile_id" json:"profile_id"`
	LocaleCode  string                `db:"locale_code" json:"locale_code"`
	Title       string                `db:"title" json:"title"`
	Description string                `db:"description" json:"description"`
	Properties  pqtype.NullRawMessage `db:"properties" json:"properties"`
}

type Question struct {
	ID            string         `db:"id" json:"id"`
	UserID        string         `db:"user_id" json:"user_id"`
	ProfileID     sql.NullString `db:"profile_id" json:"profile_id"`
	Content       string         `db:"content" json:"content"`
	IsHidden      bool           `db:"is_hidden" json:"is_hidden"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	AnsweredAt    sql.NullTime   `db:"answered_at" json:"answered_at"`
	AnswerURI     sql.NullString `db:"answer_uri" json:"answer_uri"`
	IsAnonymous   bool           `db:"is_anonymous" json:"is_anonymous"`
	AnswerKind    sql.NullString `db:"answer_kind" json:"answer_kind"`
	AnswerContent sql.NullString `db:"answer_content" json:"answer_content"`
}

type QuestionVote struct {
	ID         string    `db:"id" json:"id"`
	QuestionID string    `db:"question_id" json:"question_id"`
	UserID     string    `db:"user_id" json:"user_id"`
	Score      int32     `db:"score" json:"score"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type Session struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Story struct {
	ID              string                `db:"id" json:"id"`
	AuthorProfileID sql.NullString        `db:"author_profile_id" json:"author_profile_id"`
	Slug            string                `db:"slug" json:"slug"`
	Kind            string                `db:"kind" json:"kind"`
	Status          string                `db:"status" json:"status"`
	IsFeatured      bool                  `db:"is_featured" json:"is_featured"`
	StoryPictureURI sql.NullString        `db:"story_picture_uri" json:"story_picture_uri"`
	Title           string                `db:"title" json:"title"`
	Summary         string                `db:"summary" json:"summary"`
	Content         string                `db:"content" json:"content"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type StoryPublication struct {
	ID         string                `db:"id" json:"id"`
	StoryID    string                `db:"story_id" json:"story_id"`
	ProfileID  string                `db:"profile_id" json:"profile_id"`
	Kind       string                `db:"kind" json:"kind"`
	Properties pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt  time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type StoryTx struct {
	StoryID    string `db:"story_id" json:"story_id"`
	LocaleCode string `db:"locale_code" json:"locale_code"`
	Title      string `db:"title" json:"title"`
	Summary    string `db:"summary" json:"summary"`
	Content    string `db:"content" json:"content"`
}

type User struct {
	ID                  string         `db:"id" json:"id"`
	Kind                string         `db:"kind" json:"kind"`
	Name                string         `db:"name" json:"name"`
	Email               sql.NullString `db:"email" json:"email"`
	Phone               sql.NullString `db:"phone" json:"phone"`
	GithubHandle        sql.NullString `db:"github_handle" json:"github_handle"`
	GithubRemoteID      sql.NullString `db:"github_remote_id" json:"github_remote_id"`
	BskyHandle          sql.NullString `db:"bsky_handle" json:"bsky_handle"`
	BskyRemoteID        sql.NullString `db:"bsky_remote_id" json:"bsky_remote_id"`
	XHandle             sql.NullString `db:"x_handle" json:"x_handle"`
	XRemoteID           sql.NullString `db:"x_remote_id" json:"x_remote_id"`
	IndividualProfileID sql.NullString `db:"individual_profile_id" json:"individual_profile_id"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}
