// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (
    id,
    kind,
    NAME,
    email,
    phone,
    github_handle,
    github_remote_id,
    bsky_handle,
    bsky_remote_id,
    x_handle,
    x_remote_id,
    individual_profile_id,
    created_at,
    updated_at,
    deleted_at
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
  )
`

type CreateUserParams struct {
	ID                  string         `db:"id" json:"id"`
	Kind                string         `db:"kind" json:"kind"`
	Name                string         `db:"name" json:"name"`
	Email               sql.NullString `db:"email" json:"email"`
	Phone               sql.NullString `db:"phone" json:"phone"`
	GithubHandle        sql.NullString `db:"github_handle" json:"github_handle"`
	GithubRemoteID      sql.NullString `db:"github_remote_id" json:"github_remote_id"`
	BskyHandle          sql.NullString `db:"bsky_handle" json:"bsky_handle"`
	BskyRemoteID        sql.NullString `db:"bsky_remote_id" json:"bsky_remote_id"`
	XHandle             sql.NullString `db:"x_handle" json:"x_handle"`
	XRemoteID           sql.NullString `db:"x_remote_id" json:"x_remote_id"`
	IndividualProfileID sql.NullString `db:"individual_profile_id" json:"individual_profile_id"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

// CreateUser
//
//	INSERT INTO "user" (
//	    id,
//	    kind,
//	    NAME,
//	    email,
//	    phone,
//	    github_handle,
//	    github_remote_id,
//	    bsky_handle,
//	    bsky_remote_id,
//	    x_handle,
//	    x_remote_id,
//	    individual_profile_id,
//	    created_at,
//	    updated_at,
//	    deleted_at
//	  )
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14,
//	    $15
//	  )
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.GithubHandle,
		arg.GithubRemoteID,
		arg.BskyHandle,
		arg.BskyRemoteID,
		arg.XHandle,
		arg.XRemoteID,
		arg.IndividualProfileID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
FROM "user"
WHERE email = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetUserByEmailParams struct {
	Email sql.NullString `db:"email" json:"email"`
}

// GetUserByEmail
//
//	SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
//	FROM "user"
//	WHERE email = $1
//	  AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.GithubHandle,
		&i.GithubRemoteID,
		&i.BskyHandle,
		&i.BskyRemoteID,
		&i.XHandle,
		&i.XRemoteID,
		&i.IndividualProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
FROM "user"
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetUserByIDParams struct {
	ID string `db:"id" json:"id"`
}

// GetUserByID
//
//	SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
//	FROM "user"
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.GithubHandle,
		&i.GithubRemoteID,
		&i.BskyHandle,
		&i.BskyRemoteID,
		&i.XHandle,
		&i.XRemoteID,
		&i.IndividualProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
FROM "user"
WHERE ($1::TEXT IS NULL OR kind = ANY(string_to_array($1::TEXT, ',')))
  AND deleted_at IS NULL
`

type ListUsersParams struct {
	FilterKind sql.NullString `db:"filter_kind" json:"filter_kind"`
}

// ListUsers
//
//	SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
//	FROM "user"
//	WHERE ($1::TEXT IS NULL OR kind = ANY(string_to_array($1::TEXT, ',')))
//	  AND deleted_at IS NULL
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.FilterKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.GithubHandle,
			&i.GithubRemoteID,
			&i.BskyHandle,
			&i.BskyRemoteID,
			&i.XHandle,
			&i.XRemoteID,
			&i.IndividualProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUser = `-- name: RemoveUser :execrows
UPDATE "user"
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type RemoveUserParams struct {
	ID string `db:"id" json:"id"`
}

// RemoveUser
//
//	UPDATE "user"
//	SET deleted_at = NOW()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) RemoveUser(ctx context.Context, arg RemoveUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeUser, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE "user"
SET kind = $1,
  NAME = $2,
  email = $3,
  phone = $4,
  github_handle = $5,
  github_remote_id = $6,
  bsky_handle = $7,
  bsky_remote_id = $8,
  x_handle = $9,
  x_remote_id = $10,
  individual_profile_id = $11
WHERE id = $12
  AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Kind                string         `db:"kind" json:"kind"`
	Name                string         `db:"name" json:"name"`
	Email               sql.NullString `db:"email" json:"email"`
	Phone               sql.NullString `db:"phone" json:"phone"`
	GithubHandle        sql.NullString `db:"github_handle" json:"github_handle"`
	GithubRemoteID      sql.NullString `db:"github_remote_id" json:"github_remote_id"`
	BskyHandle          sql.NullString `db:"bsky_handle" json:"bsky_handle"`
	BskyRemoteID        sql.NullString `db:"bsky_remote_id" json:"bsky_remote_id"`
	XHandle             sql.NullString `db:"x_handle" json:"x_handle"`
	XRemoteID           sql.NullString `db:"x_remote_id" json:"x_remote_id"`
	IndividualProfileID sql.NullString `db:"individual_profile_id" json:"individual_profile_id"`
	ID                  string         `db:"id" json:"id"`
}

// UpdateUser
//
//	UPDATE "user"
//	SET kind = $1,
//	  NAME = $2,
//	  email = $3,
//	  phone = $4,
//	  github_handle = $5,
//	  github_remote_id = $6,
//	  bsky_handle = $7,
//	  bsky_remote_id = $8,
//	  x_handle = $9,
//	  x_remote_id = $10,
//	  individual_profile_id = $11
//	WHERE id = $12
//	  AND deleted_at IS NULL
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Kind,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.GithubHandle,
		arg.GithubRemoteID,
		arg.BskyHandle,
		arg.BskyRemoteID,
		arg.XHandle,
		arg.XRemoteID,
		arg.IndividualProfileID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
