receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 500

  transform/create_level_attribute:
    log_statements:
    - context: log
      statements:
        - set(attributes["level"], severity_text)

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp/pyroscope:
    endpoint: pyroscope:4040
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, transform/create_level_attribute, batch]
      exporters: [otlphttp/logs]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]

    profiles:
      receivers: [otlp]
      exporters: [otlp/pyroscope]

  telemetry:
    logs:
      level: debug
